#!/bin/bash
backupdir='/var/www/html/td'
site='www.templeos.org'
get=$(curl -s $site)
touch $backupdir/.lastget
last=$(cat $backupdir/.lastget)
if [[ "$get" != "$last"  ]] ;then
	timestamp=$(date +%s)
	wget -HkpP $backupdir/$timestamp -A png,jpg,jpeg,gif,bmp,html,PNG,JPG,JPEG,GIF,BMP,HTML $site
	echo "$get" > $backupdir/.lastget
fi
