#!/bin/bash
backupdir=''
sharedir=''
site=''
whitelist='png,jpg,jpeg,gif,bmp,html,PNG,JPG,JPEG,GIF,BMP,HTML'

touch $backupdir/.lastget

hash=$(curl -s $site | sha256sum)
last=$(cat $backupdir/.lastget)

if [[ "$hash" != "$last"  ]] ;then
        timestamp=$(date +%s)
        wget -nv -rkpP $backupdir/$timestamp -A $whitelist $site
        echo "$hash" > $backupdir/.lastget
        rsync -a $backupdir $sharedir
else
        echo "No changes"
fi
