#!/bin/bash
backupdir=''
sharedir=''
site=''

touch $backupdir/.lastget

hash=$(curl -s $site | sha256sum)
last=$(cat $backupdir/.lastget)

if [[ "$hash" != "$last"  ]] ;then
        timestamp=$(date +%s)
        wget -nv -rkpP $backupdir/$timestamp $site
        echo "$hash" > $backupdir/.lastget
        rsync -a $backupdir $sharedir
else
        echo "No changes"
fi
